swagger: '2.0'
info:
  description: Doc API de l'application de rebond smart uha
  version: "0.1"
  title: swagger_rebond_uha
  contact:
    email: contact@uha.fr
  license:
    name: Apache 2.0
    url: 'http://www.apache.org/licenses/LICENSE-2.0.html'
host: localhost:8096
basePath: /
tags:
  - name: Client
    description: calls for clients
    externalDocs:
      description: Find out more
      url: 'https://uha.fr'
schemes:
  - http
  - https
security:
  - Api_key: []
  - masterkey: []
paths:
  /opti/send:
    post:
      tags:
        - Optimisation
      summary: send informations for optimization
      description: send informations for optimization
      operation_Id: opti_send
      consumes:
        - application/json
      produces:
        - application/json
      parameters:
        - in: body
          name: optimization_json
          description: optimization informations as json object
          required: true
      responses:
        '200':
          description: Informations sent
          schema:
            type: string
          

